### ISSUE TITLE
Forked repo error

### ISSUE THREAD

**Issue by YonasBerhe** [codeforseattle/seanetmap#19]
Hey @JohnTigue I cloned your version of the original repo and tried running the node server command but I received an error when doing so. 

here is the error: 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at EventEmitter.app.listen (/home/yonas/code/seanetmap/seanetmap/node_modules/express/lib/application.js:595:24)
    at Object.<anonymous> (/home/yonas/code/seanetmap/seanetmap/server/index.js:28:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by JohnTigue** [comment]
The port is hardwired to 8000
https://github.com/codeforseattle/seanetmap/blob/master/server/index.js#L29

var server = app.listen(8000, function () {

Is it possible you have another instance already running at port 8000?
Is this persisting for you?

**Comment by YonasBerhe** [comment]
I have other programs that open up port 8000 when running a local server. Those programs where not running when I tried to run the server for your repo.

**Comment by JohnTigue** [comment]
Judging by the stack trace you provided, this really looks like the issue is that port 8000 was already busy.

http://stackoverflow.com/questions/9898372/nodejs-error-listen-eaddrinuse

Is this reproducible for you?

**Comment by JohnTigue** [comment]
Also, just to ensure that I am not confused, are we talking about:
https://github.com/JohnTigue/seanetmap

If so I am curious as to why.

**Comment by YonasBerhe** [comment]
John, you were absolutely correct I had a terminal running an instance on port 8000. It worked once I closed it.

**Comment by JohnTigue** [comment]
Sweet. Love it when they resolve easy.
